# /etc/dracut.conf.d/10-server-cloud.conf
# Ensures virtio, ENA (AWS), NVMe, and overlay drivers are in every initrd.

add_drivers+=" virtio virtio_pci virtio_blk virtio_net virtio_scsi "
add_drivers+=" nvme nvme_core ena xen_blkfront xen_netfront "
add_drivers+=" overlay btrfs "

add_dracutmodules+=" network-manager "
dracutmodules+=" systemd systemd-initrd dracut-systemd "

hostonly="no"
hostonly_cmdline="no"
reproducible="yes"
