#!/bin/bash

systemctl daemon-reload
mount -a

for service in $(systemctl list-unit-files --type=service --state=enabled --no-legend | awk '{print $1}'); do
    systemctl is-active --quiet "$service" || { echo "Starting $service..."; systemctl start "$service" &; }
done

