#!/usr/bin/env bash

for arg in "$@"; do
    case "$arg" in
        -S|-Su|-Sy|-Syu|-Syuu|-Sc|-Scc|-Sw|\
        --sync|--upgrade|--remove|-R|-Rs|-Rn|\
        -U|--upgrade|-D|--database)
            echo "Error: Shanios is an immutable distro."
            echo "System modifications (install, remove, upgrade, sync, etc.) are not permitted via pacman."
            echo "Disallowed operation: '$arg'"
            echo "Allowed operations: query (-Q/--query), file lookup (-F/--file), search (-Ss/--search), list (-Sl/--list), help (-h/--help), and version (--version)."
            echo "To install or update applications, please use Flatpak."
            echo "System updates must be performed only via shani-deploy command."
            exit 1
            ;;
    esac
done

exec /usr/bin/pacman "$@"
