#!/bin/bash
DEFAULT_EXTRA_GROUPS="input,realtime,video,sys,cups,lp,kvm,scanner"
new_args=()
provided_G=0

while [[ $# -gt 0 ]]; do
    case "$1" in
        -G)
            provided_G=1
            shift
            provided_groups="$1"
            merged_groups="${provided_groups:+${provided_groups},}${DEFAULT_EXTRA_GROUPS}"
            new_args+=("-G" "$merged_groups")
            shift
            ;;
        -G*)
            provided_G=1
            provided_groups="${1:2}"
            merged_groups="${provided_groups:+${provided_groups},}${DEFAULT_EXTRA_GROUPS}"
            new_args+=("-G" "$merged_groups")
            shift
            ;;
        *)
            new_args+=("$1")
            shift
            ;;
    esac
done

if [ $provided_G -eq 0 ]; then
    new_args+=("-G" "$DEFAULT_EXTRA_GROUPS")
fi

exec /usr/bin/useradd "${new_args[@]}"
