#!/usr/bin/env bash
# 01-configure-aws.sh — Stage 2: configure ShaniOS for AWS
#
# Sources /tmp/shanios-env.sh written by Stage 1, then chroots into @blue to:
#   - Write /etc/fstab (all Btrfs subvolumes by UUID)
#   - Reset machine-id (cloud-init regenerates on first boot)
#   - Write /etc/hostname and /etc/hosts
#   - Harden SSH for AWS key-pair access
#   - Disable Secure Boot / MOK components (not applicable on AWS)
#   - Configure cloud-init (Ec2 datasource)
#   - Install / enable AWS SSM Agent (if available in the image's pacman repos)
#   - Create the swapfile on @swap
#   - Install systemd-boot and write loader entries for @blue and @green
#   - Generate initrd via dracut inside the chroot (with foreign-chroot flags)

set -Eeuo pipefail

log()  { echo "[CONFIG-AWS][INFO]  $*"; }
warn() { echo "[CONFIG-AWS][WARN]  $*" >&2; }
die()  { echo "[CONFIG-AWS][ERROR] $*" >&2; exit 1; }

# ─────────────────────────────────────────────────────────────────────────────
# Source Stage 1 environment
# ─────────────────────────────────────────────────────────────────────────────
# shellcheck source=/dev/null
source /tmp/shanios-env.sh

CHROOT="${SHANIOS_MOUNT}"      # /mnt/shanios-target/@blue-root
ROOT_PART="${SHANIOS_ROOT_PART}"
EFI_PART="${SHANIOS_EFI_PART}"
BTRFS_MOUNT="${SHANIOS_BTRFS_MOUNT}"
BTRFS_OPTS="${SHANIOS_BTRFS_OPTS}"

[[ -d "${CHROOT}" ]]     || die "Chroot target not found: ${CHROOT}"
[[ -b "${ROOT_PART}" ]] || die "Root partition device not found: ${ROOT_PART}"
[[ -b "${EFI_PART}"  ]] || die "EFI partition device not found: ${EFI_PART}"

# ─────────────────────────────────────────────────────────────────────────────
# Helper: run a command inside the ShaniOS chroot
# ─────────────────────────────────────────────────────────────────────────────
run_chroot() {
    chroot "${CHROOT}" /bin/bash -c "$1"
}

# ─────────────────────────────────────────────────────────────────────────────
# Bind-mount pseudo-filesystems for chroot tools (dracut, systemctl, etc.)
# ─────────────────────────────────────────────────────────────────────────────
log "Bind-mounting pseudo-filesystems..."
for fs in proc sys dev run; do
    mkdir -p "${CHROOT}/${fs}"
    if ! mountpoint -q "${CHROOT}/${fs}" 2>/dev/null; then
        mount --rbind "/${fs}" "${CHROOT}/${fs}" \
            || warn "rbind /${fs} failed (non-fatal if already mounted)"
    fi
done

# Cleanup trap — always unmount pseudo-filesystems and the EFI partition
_cleanup() {
    local rc=$?
    log "Cleanup: unmounting chroot..."
    for fs in run dev sys proc; do
        mountpoint -q "${CHROOT}/${fs}" 2>/dev/null \
            && umount -lR "${CHROOT}/${fs}" 2>/dev/null || true
    done
    mountpoint -q "${CHROOT}/boot/efi" 2>/dev/null \
        && umount "${CHROOT}/boot/efi" 2>/dev/null || true
    exit "$rc"
}
trap '_cleanup' EXIT

# ─────────────────────────────────────────────────────────────────────────────
# Resolve partition UUIDs (needed for fstab and kernel cmdline)
# ─────────────────────────────────────────────────────────────────────────────
ROOT_UUID=$(blkid -s UUID -o value "${ROOT_PART}" 2>/dev/null)
EFI_UUID=$(blkid  -s UUID -o value "${EFI_PART}"  2>/dev/null)
[[ -n "${ROOT_UUID}" ]] || die "Cannot read UUID of root partition ${ROOT_PART}"
[[ -n "${EFI_UUID}"  ]] || die "Cannot read UUID of EFI partition ${EFI_PART}"
log "Root UUID: ${ROOT_UUID}"
log "EFI UUID : ${EFI_UUID}"

# ─────────────────────────────────────────────────────────────────────────────
# /etc/fstab
# Mirrors configure.sh mount_additional_subvols layout.
# Note: @root mounts at /root (root user home directory), not at /.
#       The system root (/) is @blue, declared as the subvol= in rootflags.
# ─────────────────────────────────────────────────────────────────────────────
log "Writing /etc/fstab..."
cat > "${CHROOT}/etc/fstab" << FSTAB
# /etc/fstab — generated by Packer AMI build
# <file system>    <mount point>        <type>  <options>                                           <dump> <pass>
UUID=${EFI_UUID}   /boot/efi            vfat    defaults,umask=0077                                 0      2
UUID=${ROOT_UUID}  /                    btrfs   subvol=@blue,${BTRFS_OPTS}                          0      0
UUID=${ROOT_UUID}  /root                btrfs   subvol=@root,${BTRFS_OPTS}                          0      0
UUID=${ROOT_UUID}  /home                btrfs   subvol=@home,${BTRFS_OPTS}                          0      0
UUID=${ROOT_UUID}  /data                btrfs   subvol=@data,${BTRFS_OPTS}                          0      0
UUID=${ROOT_UUID}  /nix                 btrfs   subvol=@nix,${BTRFS_OPTS}                           0      0
UUID=${ROOT_UUID}  /var/cache           btrfs   subvol=@cache,${BTRFS_OPTS}                         0      0
UUID=${ROOT_UUID}  /var/log             btrfs   subvol=@log,${BTRFS_OPTS}                           0      0
UUID=${ROOT_UUID}  /var/lib/flatpak     btrfs   subvol=@flatpak,${BTRFS_OPTS}                       0      0
UUID=${ROOT_UUID}  /var/lib/snapd       btrfs   subvol=@snapd,${BTRFS_OPTS}                         0      0
UUID=${ROOT_UUID}  /var/lib/waydroid    btrfs   subvol=@waydroid,${BTRFS_OPTS}                      0      0
UUID=${ROOT_UUID}  /var/lib/containers  btrfs   subvol=@containers,${BTRFS_OPTS}                    0      0
UUID=${ROOT_UUID}  /var/lib/machines    btrfs   subvol=@machines,${BTRFS_OPTS}                      0      0
UUID=${ROOT_UUID}  /var/lib/lxc         btrfs   subvol=@lxc,${BTRFS_OPTS}                          0      0
UUID=${ROOT_UUID}  /var/lib/lxd         btrfs   subvol=@lxd,${BTRFS_OPTS}                          0      0
UUID=${ROOT_UUID}  /var/lib/libvirt     btrfs   subvol=@libvirt,${BTRFS_OPTS},nodatacow             0      0
UUID=${ROOT_UUID}  /var/lib/qemu        btrfs   subvol=@qemu,${BTRFS_OPTS},nodatacow                0      0
UUID=${ROOT_UUID}  /swap                btrfs   subvol=@swap,defaults,noatime,nodatacow             0      0
/swap/swapfile     none                 swap    defaults                                             0      0
FSTAB
log "/etc/fstab written"

# ─────────────────────────────────────────────────────────────────────────────
# Machine ID — blank so systemd allocates a unique ID on first boot
# (standard practice for AMI golden images)
# ─────────────────────────────────────────────────────────────────────────────
log "Resetting machine-id..."
: > "${CHROOT}/etc/machine-id"

# ─────────────────────────────────────────────────────────────────────────────
# Hostname — cloud-init overwrites this on first boot from EC2 instance metadata
# ─────────────────────────────────────────────────────────────────────────────
log "Writing default hostname..."
echo "shanios" > "${CHROOT}/etc/hostname"
cat > "${CHROOT}/etc/hosts" << HOSTS
127.0.0.1   localhost
::1         localhost
127.0.1.1   shanios
HOSTS

# ─────────────────────────────────────────────────────────────────────────────
# SSH hardening for AWS key-pair access
# ─────────────────────────────────────────────────────────────────────────────
log "Writing SSH hardening config..."
mkdir -p "${CHROOT}/etc/ssh/sshd_config.d"
cat > "${CHROOT}/etc/ssh/sshd_config.d/10-aws.conf" << SSHCONF
# AWS AMI — managed by Packer build, do not edit manually
PermitRootLogin without-password
PasswordAuthentication no
ChallengeResponseAuthentication no
UsePAM yes
PrintLastLog yes
AcceptEnv LANG LC_*
Subsystem sftp /usr/lib/openssh/sftp-server
SSHCONF

# Enable sshd — try both common unit names (Arch: sshd, Debian: ssh)
run_chroot "systemctl enable sshd.service 2>/dev/null || systemctl enable ssh.service 2>/dev/null || true"

# ─────────────────────────────────────────────────────────────────────────────
# Disable Secure Boot / Shim — not applicable on AWS (no MOK enrollment)
# ─────────────────────────────────────────────────────────────────────────────
log "Disabling Secure Boot components..."
for unit in shim-boot.service mok-setup.service; do
    run_chroot "systemctl disable ${unit} 2>/dev/null || true"
done
# Remove MOK key from EFI — AWS boots via its own hypervisor chain
rm -f "${CHROOT}/boot/efi/EFI/BOOT/MOK.der" 2>/dev/null || true

# ─────────────────────────────────────────────────────────────────────────────
# cloud-init — Ec2 datasource configuration
#
# ShaniOS is Arch-based. cloud-init may or may not be pre-installed in the
# image profile. We do NOT attempt a pacman install here because:
#   - pacman inside a foreign chroot requires keyring initialization + network
#   - Both are unreliable in the Packer build environment
# If cloud-init is absent, log a clear warning and continue. Users who need
# it should add cloud-init to their image_profiles/<profile>/package-list.txt.
# ─────────────────────────────────────────────────────────────────────────────
log "Configuring cloud-init..."
if run_chroot "command -v cloud-init" &>/dev/null; then
    mkdir -p "${CHROOT}/etc/cloud/cloud.cfg.d"
    cat > "${CHROOT}/etc/cloud/cloud.cfg.d/10-shanios-aws.cfg" << CLOUDINIT
# ShaniOS AWS cloud-init — generated by Packer build
datasource_list: [Ec2, None]

system_info:
  default_user:
    name: shanios
    shell: /bin/zsh
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    groups: [wheel, sys, video, input, kvm, lxd, libvirt, sambashare]
    lock_passwd: true

cloud_final_modules:
  - [scripts-vendor, always]
  - [scripts-per-once, always]
  - [scripts-per-boot, always]
  - [scripts-per-instance, always]
  - [scripts-user, always]
  - [ssh-authkey-fingerprints, always]
  - [final-message, always]
CLOUDINIT

    run_chroot "systemctl enable \
        cloud-init-local.service \
        cloud-init.service \
        cloud-config.service \
        cloud-final.service 2>/dev/null || true"
    log "cloud-init configured"
else
    warn "cloud-init not found in the ShaniOS image."
    warn "Add 'cloud-init' to image_profiles/<profile>/package-list.txt and rebuild the base image."
fi

# ─────────────────────────────────────────────────────────────────────────────
# AWS SSM Agent — same caveat as cloud-init above
# ─────────────────────────────────────────────────────────────────────────────
log "Checking for AWS SSM Agent..."
if run_chroot "command -v amazon-ssm-agent" &>/dev/null; then
    run_chroot "systemctl enable amazon-ssm-agent 2>/dev/null || true"
    log "SSM Agent enabled"
else
    warn "amazon-ssm-agent not found in the ShaniOS image."
    warn "Add 'amazon-ssm-agent' to image_profiles/<profile>/package-list.txt (available via AUR)"
    warn "or use AWS Systems Manager Session Manager via EC2 Instance Connect instead."
fi

# ─────────────────────────────────────────────────────────────────────────────
# Swapfile on the @swap Btrfs subvolume
# ─────────────────────────────────────────────────────────────────────────────
log "Creating swapfile on @swap subvolume..."
SWAP_SUBVOL="${BTRFS_MOUNT}/@swap"

if [[ -d "${SWAP_SUBVOL}" ]]; then
    # Cap at 4 GiB — suitable for the builder instance RAM
    SWAP_MB=$(free -m | awk '/^Mem:/{m=$2; print (m>4096) ? 4096 : m}')
    log "Swapfile size: ${SWAP_MB} MiB"

    SWAPFILE="${SWAP_SUBVOL}/swapfile"
    # Prefer btrfs mkswapfile (kernel ≥ 6.1 + btrfs-progs ≥ 6.1)
    if btrfs filesystem mkswapfile --size "${SWAP_MB}M" "${SWAPFILE}" 2>/dev/null; then
        log "Swapfile created via btrfs mkswapfile"
    else
        warn "btrfs mkswapfile unavailable — using dd fallback"
        dd if=/dev/zero of="${SWAPFILE}" bs=1M count="${SWAP_MB}" status=progress
        chmod 600 "${SWAPFILE}"
        # Ensure no-COW on the file itself (chattr on the directory may not propagate)
        chattr +C "${SWAPFILE}" 2>/dev/null || true
        mkswap "${SWAPFILE}"
    fi
    log "Swapfile ready: ${SWAPFILE}"
else
    warn "@swap subvolume not found at ${SWAP_SUBVOL} — skipping swapfile creation"
fi

# ─────────────────────────────────────────────────────────────────────────────
# systemd-boot: install bootloader onto the EFI partition
# ─────────────────────────────────────────────────────────────────────────────
log "Installing systemd-boot..."
if run_chroot "command -v bootctl" &>/dev/null; then
    # bootctl install needs /boot/efi mounted — it is (from Stage 1)
    run_chroot "bootctl install --esp-path=/boot/efi 2>&1" \
        || warn "bootctl install failed — EFI partition may need manual bootloader setup"
else
    warn "bootctl not found in the ShaniOS image — skipping bootloader install"
fi

mkdir -p "${CHROOT}/boot/efi/loader"
cat > "${CHROOT}/boot/efi/loader/loader.conf" << LOADER
# systemd-boot loader config — generated by Packer build
# The default entry uses a glob so it matches regardless of the tries counter
# (shanios-blue+3-0.conf → shanios-blue+2-1.conf → ... after each successful boot)
default shanios-blue*.conf
timeout 3
console-mode max
editor  0
auto-entries 0
beep 0
LOADER

# ─────────────────────────────────────────────────────────────────────────────
# Kernel detection
# ─────────────────────────────────────────────────────────────────────────────
KERNEL_VER=$(
    ls -1 "${CHROOT}/usr/lib/modules/" 2>/dev/null \
    | grep -E '^[0-9]' \
    | sort -V \
    | tail -1 \
    || true
)

if [[ -z "${KERNEL_VER}" ]]; then
    warn "No kernel found in ${CHROOT}/usr/lib/modules/ — skipping initrd generation and boot entries."
    warn "The AMI will boot but will need a manual bootloader setup."
    exit 0
fi
log "Kernel version: ${KERNEL_VER}"

# ─────────────────────────────────────────────────────────────────────────────
# Kernel command line for each slot
# AWS Nitro does not require 'ro'; the ShaniOS root is read-only by design
# (systemd.volatile=state provides a tmpfs /var overlay at runtime).
# ─────────────────────────────────────────────────────────────────────────────
COMMON_OPTS="quiet splash systemd.volatile=state"

for slot in blue green; do
    CMDLINE="root=UUID=${ROOT_UUID} rootfstype=btrfs rootflags=subvol=@${slot},${BTRFS_OPTS} ro ${COMMON_OPTS}"
    log "Kernel cmdline for @${slot}: ${CMDLINE}"

    # Write the cmdline file that dracut and gen-efi.sh read
    mkdir -p "${CHROOT}/etc/kernel"
    echo "${CMDLINE}" > "${CHROOT}/etc/kernel/install_cmdline_${slot}"
done

# ─────────────────────────────────────────────────────────────────────────────
# dracut — generate initrd inside the chroot
#
# Foreign-chroot flags:
#   --no-kernel     skip host kernel module tree (we use the image's modules)
#   --kver          explicit kernel version (no detection against running kernel)
#   --hostonly=no   generic initrd (we do not know the target hardware at AMI build time)
#   --add-drivers   include btrfs explicitly (not always auto-detected in foreign chroot)
#   --omit          remove modules that require the live host (e.g. lvm2 is fine but
#                   some dracut modules probe /sys which is rbind-mounted — guard with care)
# ─────────────────────────────────────────────────────────────────────────────
if run_chroot "command -v dracut" &>/dev/null; then
    EFI_SHANIOS_DIR="/boot/efi/EFI/shanios"

    for slot in blue green; do
        CMDLINE=$(cat "${CHROOT}/etc/kernel/install_cmdline_${slot}")
        INITRD_PATH="${EFI_SHANIOS_DIR}/${KERNEL_VER}/initrd-${slot}.img"
        VMLINUZ_DEST="${EFI_SHANIOS_DIR}/${KERNEL_VER}/linux"

        log "Generating initrd for @${slot}..."
        run_chroot "
            set -e
            mkdir -p '${EFI_SHANIOS_DIR}/${KERNEL_VER}'
            dracut \
                --force \
                --no-kernel \
                --kver '${KERNEL_VER}' \
                --kernel-cmdline '${CMDLINE}' \
                --add-drivers 'btrfs overlay' \
                --hostonly=no \
                --reproducible \
                '${INITRD_PATH}'
        " || warn "dracut failed for @${slot} — initrd may be missing"

        # Copy vmlinuz to EFI partition (only need it once, but idempotent)
        if [[ -f "${CHROOT}/usr/lib/modules/${KERNEL_VER}/vmlinuz" ]]; then
            cp "${CHROOT}/usr/lib/modules/${KERNEL_VER}/vmlinuz" \
               "${CHROOT}${VMLINUZ_DEST}" 2>/dev/null \
               || warn "vmlinuz copy failed for @${slot}"
        else
            warn "vmlinuz not found at ${CHROOT}/usr/lib/modules/${KERNEL_VER}/vmlinuz"
        fi

        # systemd-boot loader entry (plain — no tries counter; gen-efi.sh adds +3-0)
        mkdir -p "${CHROOT}/boot/efi/loader/entries"
        cat > "${CHROOT}/boot/efi/loader/entries/shanios-${slot}.conf" << ENTRY
title   ShaniOS (${slot})
linux   /EFI/shanios/${KERNEL_VER}/linux
initrd  /EFI/shanios/${KERNEL_VER}/initrd-${slot}.img
options ${CMDLINE}
ENTRY
        log "Boot entry written: shanios-${slot}.conf"
    done
else
    warn "dracut not found in the ShaniOS image."
    warn "Add 'dracut' to image_profiles/<profile>/package-list.txt and rebuild the base image."
    warn "The AMI will not boot without an initrd."
fi

log "AWS configuration complete"
