name: Build

on:
  push:
    branches: [main]
    paths:
      - 'scripts/**'
      - 'image_profiles/**'
      - 'iso_profiles/**'
      - 'config/**'
      - 'build.sh'
      - 'run_in_container.sh'
      - '.github/workflows/build.yml'
  workflow_dispatch:
    inputs:
      profile:
        description: "Image profile"
        required: true
        default: "gnome"
        type: choice
        options: [cosmic, gnome, plasma, server, shared, kiosk]

jobs:
  build:
    uses: shani8dev/shani-ci-commons/.github/workflows/build.yml@main
    with:
      docker-image: "docker.io/shrinivasvkumbhar/shani-builder"
      build-command: "build.sh image -p ${{ github.event.inputs.profile || 'gnome' }}"
      runtime: "docker"
