name: Notify Telegram

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Notification message'
        required: false
        default: 'Build notification'
      status:
        description: 'Status (started, failed, success)'
        required: true
        type: choice
        options: [started, failed, success]
      repo-name:
        description: 'Display name of the repo'
        required: true
        type: string
        default: 'ShaniOS Install Media'

jobs:
  notify:
    uses: shani8dev/shani-ci-commons/.github/workflows/notify-telegram.yml@main
    with:
      message: ${{ inputs.message }}
      status: ${{ inputs.status }}
      repo-name: ${{ inputs.repo-name }}
    secrets:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
